"""Add datestamp column

Revision ID: 0223fb3b00b6
Revises: 2afe6c4ef6fa
Create Date: 2024-04-22 21:11:14.166528

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0223fb3b00b6"
down_revision: Union[str, None] = "2afe6c4ef6fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("datestamp", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "datestamp")
    # ### end Alembic commands ###
