"""base

Revision ID: 235fcc32d768
Revises:
Create Date: 2024-04-22 21:00:41.160877

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "235fcc32d768"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
