"""Add filetype column

Revision ID: 2afe6c4ef6fa
Revises: 235fcc32d768
Create Date: 2024-04-22 21:05:30.952753

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2afe6c4ef6fa"
down_revision: Union[str, None] = "235fcc32d768"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("filetype", sa.Enum("image", "video", "unknown", name="mediatype"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "filetype")
    # ### end Alembic commands ###
